### ISSUE TITLE
Ensure telemetrydb.sql is Properly Copied on Fresh Install of Faraday Software

### ISSUE THREAD

**Issue by kb1lqc** [FaradayRF/Faraday-Software#226] opened 2017-07-04 14:51 UTC
## Summary
@kb1lqd is still [reporting](https://github.com/FaradayRF/Faraday-Software/pull/222#discussion_r125405271) that this issue exists. It's being reported on line [626 of telemetry.py](https://github.com/FaradayRF/Faraday-Software/blob/master/faraday/telemetry.py#L626) which should fail gracefully with an exception that is caught. Additionally, it appears that the [schemaname is correct](https://github.com/FaradayRF/Faraday-Software/blob/master/etc/faraday/telemetry.sample.ini#L7) in telemetry.sample.ini... 

## Problem Explanation
N/A

#### Software 
Faraday Master Branch and issue220 of kb1lqc fork

#### Hardware
N/A

# Supporting Information

![27819576-c77ad662-604f-11e7-9a94-ed8e3a945273](https://user-images.githubusercontent.com/331540/27834695-d1665074-608c-11e7-8d09-05c87ee0af35.png)

**Comment by kb1lqc** [comment] 2017-07-04 18:28
Used latest Master Branch with `pip install .` resulting in:

```
$ pip show faraday
Name: faraday
Version: 0.0.1014.dev1121
Summary: FaradayRF amateur radio open source software
Home-page: https://github.com/FaradayRF/Faraday-Software
Author: FaradayRF
Author-email: Support@FaradayRF.com
License: GPLv3
Location: c:\python27\lib\site-packages
Requires: enum34, itsdangerous, pycodestyle, pyserial, MarkupSafe, pytest, Jinja2, click, requests, flake8, pyparsing, py, six, Flask, Werkzeug, packaging, mccabe, configparser, appdirs, pyflakes, Flask-Cors, pytest-flake8
```

Telemetry worked fine. Cannot reproduce.

**Comment by kb1lqd** [comment] 2017-07-05 21:36
Verified it has been working for me again on latest installations, I also cannot reproduce so I am closing this. Hopefully this was a fluke or user-error on my part :|

**Closed as completed by kb1lqd** 2017-07-05 21:36 UTC
Labels: bug
